<?php
namespace home\controllers;

use Yii;
use yii\web\Controller;

class IndexController extends Controller{
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        return $this->render('index');
    }
}