<?php
namespace home\controllers;

use Yii;
use yii\web\Controller;

class SiteController extends Controller{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        return $this->render('Index');
    }

    public function actionError(){
        return $this->render('error');
    }
}