<?php
namespace home\controllers;

use Yii;
use yii\web\Controller;

class SiteController extends Controller{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){}
}