<?php
namespace admin\controllers;

use Yii;

class IndexController extends BaseController{
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        return $this->render('index');
    }
}