<?php
namespace admin\controllers;

use Yii;
use yii\web\Controller;
use admin\models\Admin;

class LoginController extends Controller{
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 登录
     * @return string
     */
    public function actionIndex(){
        //if(true){}
        
        return $this->renderPartial('login');
    }


}