<?php
namespace admin\controllers;

use Yii;
use yii\web\Controller;

class LoginController extends Controller{
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        return $this->renderPartial('login');
    }
}