<?php
namespace admin\controllers;

use Yii;
use yii\web\Controller;
use admin\models\Admin;
use admin\models\formes\AdminLoginForm;

class LoginController extends BaseController{
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 登录
     * @return string
     */
    public function actionIndex(){
        //if(true){}
        //$list = Admin::findOne(1);
        //var_dump($list);exit;
        //if(){}
        $model = new AdminLoginForm();
        return $this->renderPartial('login',['model'=>$model]);
    }
    

}